### PR TITLE
Add webpack-notifier plugin as an optional extra in development

### PR DESCRIPTION
**Pull request by makenosound**
pasted_image_at_2015_07_23_11_29_am_360

It’s relatively smart. If you cause an error/warning it’ll alert you, and the first time it builds successfully after an error/warning it’ll let you know that the build was successful.

I’ve made it so you can disable using a `ENV` variable: `ASSETS_NOTIFIER_ENABLED=false`.

### CODE REVIEW

**Comment by timriley** [comment]
Nice, @makenosound! Does this need a tool to be installed for it to work? Perhaps we could add that to the README?

On the env var, I wonder if we could invert it and make it `DISABLE_ASSETS_NOTIFIER`, so it's consistent with Rails’ `DISABLE_SPRING`? Then it'd just need any truthy value in order for it to do its thing.

**Comment by makenosound** [comment]
> Does this need a tool to be installed for it to work?

Not as far as I’m aware — I just `npm install`ed and it worked.

And yep, makes sense to invert the `ENV`. I’ll fix that up.

**Comment by makenosound** [comment]
@timriley That `ENV` is flipped now.

**Comment by timriley** [comment]
Thanks @makenosound. One more thing, though: I think it'd be easiest to use if we:

1. Removed it from `.env.example`
2. Make it so that _any_ value for that ENV var disabled the feature. Shell vars like this are not intuitive, so it'd be best if we could work in the widest possible set of cases.

For example, I'd been doing `DISABLE_SPRING=yes rails console` in my shell to disable Spring occasionally. If the input requirements for that var were as strict as they are at the moment, that wouldn't even work. What do you think?

**Comment by makenosound** [comment]
@timriley Ah, sure. Adjusted that now — you can set anything (even `false`) for that now and it’ll disable the notifier.

**Comment by timriley** [comment]
@makenosound Excellent! Looks great, let's merge this.

**Pull request merged**
